---
- name: Check if osd_devices attribute exists
  shell: "{{knife_command}} search node \"name:{{inventory_hostname}}\" -a ceph.osd_devices | grep {{disk}}"
  register: result
  ignore_errors: True
  delegate_to: "{{groups.chef[0]}}"

- name: Create osd_devices attribute
  command: "{{knife_command}} exec -E \"@n=Chef::Node.load('{{inventory_hostname}}') ; a=@n.normal ; a['ceph']['osd_devices']=[{'device' => '{{disk}}'}];;@n.save\""
  when: result|failed and "/dev/" in disk
  delegate_to: "{{groups.chef[0]}}"

- name: Create osd_devices attribute
  command: "{{knife_command}} exec -E \"@n=Chef::Node.load('{{item}}') ; a=@n.normal ; a['ceph']['osd_devices']=[{'device' => '{{disk}}', 'type' => 'directory'}];;@n.save\""
  with_items: groups.ceph
  when: result|failed and not "/dev/" in disk
  delegate_to: "{{groups.chef[0]}}"

- name: Create OSD Dir
  file: path=disk state=directory
  when: not "/dev/" in disk

- name: Add ceph-osd role
  command: "{{knife_command}} node run_list add {{inventory_hostname}} role[ceph-osd]"
  delegate_to: "{{groups.chef[0]}}"

- name: Wait for Solr cache
  command: "{{knife_command}} exec -E \"nodes.search('role:ceph-mon AND ceph_bootstrap_osd_key:*') {|n| puts n.name}\""
  register: output
  until: output.stdout != ""
  retries: 24
  delay: 5
  changed_when: output.stdout != ""
  when: result|failed
  delegate_to: "{{groups.chef[0]}}"

- name: Run chef-client
  command: chef-client

- name: Activate disk
  shell: "/usr/sbin/ceph-disk-activate {{disk}}; service ceph-osd-all restart; /etc/init.d/ceph restart; pgrep -fl osd"
  register: result
  retries: 10
  delay: 0
  until: result.rc == 0

- name: Run chef-client
  command: chef-client

