- name: Gather facts
  setup:

- name: Update /etc/hosts
  command: "sed -i 's/{{buildid}}-{{inventory_hostname}}/{{inventory_hostname}}/g' /etc/hosts"

- name: Update /etc/hostname
  command: "sed -i 's/{{buildid}}-{{inventory_hostname}}/{{inventory_hostname}}/g' /etc/hostname"
  when: ansible_os_family == "Debian"

- name: Update /etc/hostname
  command: "sed -i 's/{{buildid}}-{{inventory_hostname}}/{{inventory_hostname}}/g' /etc/sysconfig/network"
  when: ansible_os_family == "RedHat"

- name: Set hostname
  command: "hostname {{inventory_hostname}}"


- name: Clear ruleset
  shell: "{{item}}-restore < /dev/null"
  with_items:
  - iptables
  - ip6tables
  when: ansible_os_family == "RedHat"

- name: Stop iptables
  service: name={{item}} state=stopped enabled=no
  with_items:
  - iptables
  - ip6tables
  when: ansible_os_family == "RedHat"

- name: Save empty ruleset
  shell: "{{item}}-save > /etc/sysconfig/{{item}}"
  with_items:
  - iptables
  - ip6tables
  when: ansible_os_family == "RedHat"

# Workaround RHEL/Centos Qemu bug https://bugzilla.redhat.com/show_bug.cgi?id=1039024
- name: Remove old qemu packages
  command: rpm -e qemu-kvm qemu-img --nodeps
  when: ansible_os_family == "RedHat"
  ignore_errors: true

- name: Install RHEV qemu packages
  yum: name="{{item}}" state="present"
  with_items:
      - "http://93e60379985364bc13d8-5b5a0c83cc897bb17fca4c14d2dcd583.r59.cf3.rackcdn.com/qemu-img-rhev-0.12.1.2-2.415.el6.x86_64.rpm"
      - "http://93e60379985364bc13d8-5b5a0c83cc897bb17fca4c14d2dcd583.r59.cf3.rackcdn.com/qemu-kvm-rhev-0.12.1.2-2.415.el6.x86_64.rpm"
  when: ansible_os_family == "RedHat"

- name: Symlink /usr/lib64/qemu/librbd.so.1 to /usr/lib64/librbd.so.1
  file: src=/usr/lib64/librbd.so.1 dest=/usr/lib64/qemu/librbd.so.1 state=link
  when: ansible_os_family == "RedHat"
