- name: Clone chef-cookbooks
  git: repo=https://github.com/rcbops/chef-cookbooks dest={{ansible_env.HOME}}/chef-cookbooks version=master

- name: Upload cookbooks
  command: "{{knife_command}} cookbook upload -o chef-cookbooks/cookbooks -a"

- name: Upload roles
  shell: "{{knife_command}} role from_file chef-cookbooks/roles/*.rb"

- name: Generate chef environment from template
  template: src=havana.json.j2 dest={{ansible_env.HOME}}/havana.json

- name: Upload environment
  command: "{{knife_command}} environment from_file havana.json"
